### ISSUE TITLE
[Bug] Plugin using remote library

### ISSUE THREAD

**Issue by zerebos** [BinaryQuantumSoul/discord-latex#1]
Hey there your plugin was denied with reason: 
> This remotely links a library, see guidelines security & privacy #5.

This is referring to point number 5 of our Security & Privacy guidelines for plugins as seen here: https://docs.betterdiscord.app/plugins/introduction/guidelines#security--privacy

Please consider bundling the library you are using rather than remotely linking it. Once you do I'd love to see this plugin resubmitted! I think this is much better than our current LaTeX plugin.

**Comment by BinaryQuantumSoul** [comment]
> Please consider bundling the library you are using rather than remotely linking it

I've been trying for a while but I'm not able to :/ 
Since you're experienced with this, would you mind looking at the [related issue](https://github.com/mathjax/MathJax/issues/3079)?  I'd be very glad. Maybe it's a common issue for BetterDiscord plugins. You know the internals better than me. I'm new to both BetterDiscord and JavaScript :D

**Comment by BinaryQuantumSoul** [comment]
Fixed in last version

**Comment by BinaryQuantumSoul** [comment]
Fixed* in latest version
